site_name: iaEditais
repo_url: https://github.com/meirelesgc/fiotec-iaEditais.git
repo_name: meirelesgc/fiotec-iaEditais

nav:
  - 'Introdução': index.md
  - 'Demonstração': 
    - 'Introdução': resources/index.md
    - 'Árvore de verificação': resources/tree.md
    - 'Analise': resources/analysis.md
  - 'Desenvolvimento': 
    - 'Ambiente': dev/index.md
    - 'Arquitetura': dev/architecture.md
    - 'Banco de Dados': dev/database.md
  - 'Referência da API': api/index.md

theme:
  name: material
  palette:
    primary: teal
    scheme: slate
    accent: deep orange
  language: pt-BR
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.extra
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
plugins:
    - search
    - mermaid2