"""empty message

Revision ID: 04f324aaecb3
Revises: ce1e18927f47
Create Date: 2025-09-19 14:29:32.313513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f324aaecb3'
down_revision: Union[str, Sequence[str], None] = 'ce1e18927f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_editors',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_doc_editor_document_id'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name='fk_doc_editor_granted_by'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_doc_editor_user_id'),
    sa.PrimaryKeyConstraint('document_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_editors')
    # ### end Alembic commands ###
