"""descrição humanizada para os logs

Revision ID: 06d6dae7c62b
Revises: 43508ecdaeda
Create Date: 2026-01-31 19:10:03.821796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d6dae7c62b'
down_revision: Union[str, Sequence[str], None] = '43508ecdaeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'description')
    # ### end Alembic commands ###
