"""fox: regra de unicidade nos documentos

Revision ID: 0a610a127891
Revises: fce075e65e07
Create Date: 2026-02-07 10:06:46.981609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a610a127891'
down_revision: Union[str, Sequence[str], None] = 'fce075e65e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uq_documents_name_active'), table_name='documents', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_uq_documents_name_active'), 'documents', ['name'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
