"""remove_input_from_test_cases

Revision ID: 0d897444b2a4
Revises: 20ac25fed6c6
Create Date: 2026-01-10 09:46:57.495567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d897444b2a4'
down_revision: Union[str, Sequence[str], None] = '20ac25fed6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'input')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('input', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
