"""empty message

Revision ID: 382e87b0eb8e
Revises: b8d6d5117196
Create Date: 2026-04-30 20:37:29.292606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382e87b0eb8e'
down_revision: Union[str, Sequence[str], None] = 'b8d6d5117196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_bundles_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_bundles_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_bundles_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundle_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bundle_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_bundle_documents_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_bundle_documents_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_bundle_documents_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundle_document_typifications',
    sa.Column('bundle_document_id', sa.Uuid(), nullable=False),
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_document_id'], ['bundle_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['typification_id'], ['typifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_document_id', 'typification_id')
    )
    op.create_foreign_key('fk_system_settings_deleted_by', 'system_settings', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_system_settings_updated_by', 'system_settings', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_system_settings_created_by', 'system_settings', 'users', ['created_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_system_settings_created_by', 'system_settings', type_='foreignkey')
    op.drop_constraint('fk_system_settings_updated_by', 'system_settings', type_='foreignkey')
    op.drop_constraint('fk_system_settings_deleted_by', 'system_settings', type_='foreignkey')
    op.drop_table('bundle_document_typifications')
    op.drop_table('bundle_documents')
    op.drop_table('bundles')
    # ### end Alembic commands ###
