"""quebrando regras de unicidade

Revision ID: 39015d7b52aa
Revises: 167e5c361c80
Create Date: 2026-02-11 15:48:50.621589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39015d7b52aa'
down_revision: Union[str, Sequence[str], None] = '167e5c361c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uq_branch_title_active'), table_name='branches', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_uq_branch_taxonomy_title_active', 'branches', ['taxonomy_id', 'title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_uq_taxonomies_title_active'), table_name='taxonomies', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_uq_taxonomies_typification_title_active', 'taxonomies', ['title', 'typification_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_taxonomies_typification_title_active', table_name='taxonomies', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_uq_taxonomies_title_active'), 'taxonomies', ['title'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_uq_branch_taxonomy_title_active', table_name='branches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_uq_branch_title_active'), 'branches', ['title'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
