"""salvando dados do presidio

Revision ID: 3d3b9056c217
Revises: dad9f0782cdf
Create Date: 2025-11-13 18:28:04.861279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3b9056c217'
down_revision: Union[str, Sequence[str], None] = 'dad9f0782cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applied_branches', sa.Column('presidio_mapping', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applied_branches', 'presidio_mapping')
    # ### end Alembic commands ###
