"""empty message

Revision ID: 4dbbbd067820
Revises: 5b4d2b6591d5
Create Date: 2025-09-19 18:47:51.017192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbbbd067820'
down_revision: Union[str, Sequence[str], None] = '5b4d2b6591d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_sources',
    sa.Column('taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_tax_source_created_by'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_tax_source_source_id'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomies.id'], name='fk_tax_source_taxonomy_id'),
    sa.PrimaryKeyConstraint('taxonomy_id', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxonomy_sources')
    # ### end Alembic commands ###
