"""

Revision ID: 517707af7e79
Revises: b8abf8d05ac6
Create Date: 2025-09-11 21:40:07.497919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517707af7e79'
down_revision: Union[str, Sequence[str], None] = 'b8abf8d05ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('branches', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('branches', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_branch_created_by', 'branches', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_branch_updated_by', 'branches', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('fk_branch_deleted_by', 'branches', 'users', ['deleted_by'], ['id'])
    op.add_column('docs', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('docs', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('docs', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_doc_created_by', 'docs', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_doc_deleted_by', 'docs', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_doc_updated_by', 'docs', 'users', ['updated_by'], ['id'])
    op.add_column('sources', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('sources', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('sources', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_source_deleted_by', 'sources', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_source_created_by', 'sources', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_source_updated_by', 'sources', 'users', ['updated_by'], ['id'])
    op.add_column('taxonomies', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('taxonomies', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('taxonomies', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_taxonomy_updated_by', 'taxonomies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('fk_taxonomy_deleted_by', 'taxonomies', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_taxonomy_created_by', 'taxonomies', 'users', ['created_by'], ['id'])
    op.add_column('typification_sources', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_typ_source_created_by', 'typification_sources', 'users', ['created_by'], ['id'])
    op.add_column('typifications', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('typifications', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('typifications', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_typification_created_by', 'typifications', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_typification_deleted_by', 'typifications', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_typification_updated_by', 'typifications', 'users', ['updated_by'], ['id'])
    op.add_column('units', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('units', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('units', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_unit_updated_by', 'units', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_unit_deleted_by', 'units', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_unit_created_by', 'units', 'users', ['created_by'], ['id'], use_alter=True)
    op.add_column('users', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_user_deleted_by', 'users', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_user_created_by', 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_user_updated_by', 'users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_updated_by', 'users', type_='foreignkey')
    op.drop_constraint('fk_user_created_by', 'users', type_='foreignkey')
    op.drop_constraint('fk_user_deleted_by', 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_constraint('fk_unit_created_by', 'units', type_='foreignkey')
    op.drop_constraint('fk_unit_deleted_by', 'units', type_='foreignkey')
    op.drop_constraint('fk_unit_updated_by', 'units', type_='foreignkey')
    op.drop_column('units', 'deleted_by')
    op.drop_column('units', 'updated_by')
    op.drop_column('units', 'created_by')
    op.drop_constraint('fk_typification_updated_by', 'typifications', type_='foreignkey')
    op.drop_constraint('fk_typification_deleted_by', 'typifications', type_='foreignkey')
    op.drop_constraint('fk_typification_created_by', 'typifications', type_='foreignkey')
    op.drop_column('typifications', 'deleted_by')
    op.drop_column('typifications', 'updated_by')
    op.drop_column('typifications', 'created_by')
    op.drop_constraint('fk_typ_source_created_by', 'typification_sources', type_='foreignkey')
    op.drop_column('typification_sources', 'created_by')
    op.drop_constraint('fk_taxonomy_created_by', 'taxonomies', type_='foreignkey')
    op.drop_constraint('fk_taxonomy_deleted_by', 'taxonomies', type_='foreignkey')
    op.drop_constraint('fk_taxonomy_updated_by', 'taxonomies', type_='foreignkey')
    op.drop_column('taxonomies', 'deleted_by')
    op.drop_column('taxonomies', 'updated_by')
    op.drop_column('taxonomies', 'created_by')
    op.drop_constraint('fk_source_updated_by', 'sources', type_='foreignkey')
    op.drop_constraint('fk_source_created_by', 'sources', type_='foreignkey')
    op.drop_constraint('fk_source_deleted_by', 'sources', type_='foreignkey')
    op.drop_column('sources', 'deleted_by')
    op.drop_column('sources', 'updated_by')
    op.drop_column('sources', 'created_by')
    op.drop_constraint('fk_doc_updated_by', 'docs', type_='foreignkey')
    op.drop_constraint('fk_doc_deleted_by', 'docs', type_='foreignkey')
    op.drop_constraint('fk_doc_created_by', 'docs', type_='foreignkey')
    op.drop_column('docs', 'deleted_by')
    op.drop_column('docs', 'updated_by')
    op.drop_column('docs', 'created_by')
    op.drop_constraint('fk_branch_deleted_by', 'branches', type_='foreignkey')
    op.drop_constraint('fk_branch_updated_by', 'branches', type_='foreignkey')
    op.drop_constraint('fk_branch_created_by', 'branches', type_='foreignkey')
    op.drop_column('branches', 'deleted_by')
    op.drop_column('branches', 'updated_by')
    op.drop_column('branches', 'created_by')
    # ### end Alembic commands ###
