"""adicionando indices com where

Revision ID: 5b4d2b6591d5
Revises: f27a3617d826
Create Date: 2025-09-19 18:16:12.805933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4d2b6591d5'
down_revision: Union[str, Sequence[str], None] = 'f27a3617d826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_uq_branch_title_active', 'branches', ['title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_documents_identifier_active', 'documents', ['identifier'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_documents_name_active', 'documents', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_sources_name_active', 'sources', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_taxonomies_title_active', 'taxonomies', ['title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_typifications_name_active', 'typifications', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_units_name_active', 'units', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_users_phone_number_active', 'users', ['phone_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_users_phone_number_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_units_name_active', table_name='units', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_typifications_name_active', table_name='typifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_taxonomies_title_active', table_name='taxonomies', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_sources_name_active', table_name='sources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_documents_name_active', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_documents_identifier_active', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_taxonomies_title_active', table_name='branches', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
