"""make doc_id required in test_cases

Revision ID: 5dc8a7f2040b
Revises: 4a301c46a1fe
Create Date: 2025-10-25 14:33:08.306892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc8a7f2040b'
down_revision: Union[str, Sequence[str], None] = '4a301c46a1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_cases', 'doc_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_cases', 'doc_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
