"""

Revision ID: 72df5d6c7400
Revises: 85d08c533394
Create Date: 2025-09-13 09:57:59.237453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72df5d6c7400'
down_revision: Union[str, Sequence[str], None] = '85d08c533394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_typifications',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_doc_typ_created_by'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_doc_typ_document_id'),
    sa.ForeignKeyConstraint(['typification_id'], ['typifications.id'], name='fk_doc_typ_typification_id'),
    sa.PrimaryKeyConstraint('document_id', 'typification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_typifications')
    # ### end Alembic commands ###
