"""colunas tsv

Revision ID: 7efe5b245c25
Revises: 0a610a127891
Create Date: 2026-02-09 17:57:53.356974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7efe5b245c25'
down_revision: Union[str, Sequence[str], None] = '0a610a127891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', title) || to_tsvector('portuguese', coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('ix_branches_tsv', 'branches', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('documents', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', name) || to_tsvector('portuguese', identifier) || to_tsvector('portuguese', coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('ix_documents_tsv', 'documents', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('sources', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', name) || to_tsvector('portuguese', coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('ix_sources_tsv', 'sources', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('taxonomies', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', title) || to_tsvector('portuguese', coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('ix_taxonomies_tsv', 'taxonomies', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('typifications', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', name)", persisted=True), nullable=False))
    op.create_index('ix_typifications_tsv', 'typifications', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('units', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('portuguese', name), 'A') || setweight(to_tsvector('portuguese', coalesce(location, '')), 'B')", persisted=True), nullable=False))
    op.create_index('ix_units_tsv', 'units', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('users', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('simple', username), 'A')", persisted=True), nullable=False))
    op.create_index('ix_users_tsv', 'users', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_tsv', table_name='users', postgresql_using='gin')
    op.drop_column('users', 'tsv')
    op.drop_index('ix_units_tsv', table_name='units', postgresql_using='gin')
    op.drop_column('units', 'tsv')
    op.drop_index('ix_typifications_tsv', table_name='typifications', postgresql_using='gin')
    op.drop_column('typifications', 'tsv')
    op.drop_index('ix_taxonomies_tsv', table_name='taxonomies', postgresql_using='gin')
    op.drop_column('taxonomies', 'tsv')
    op.drop_index('ix_sources_tsv', table_name='sources', postgresql_using='gin')
    op.drop_column('sources', 'tsv')
    op.drop_index('ix_documents_tsv', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'tsv')
    op.drop_index('ix_branches_tsv', table_name='branches', postgresql_using='gin')
    op.drop_column('branches', 'tsv')
    # ### end Alembic commands ###
