"""mensagens para documentos

Revision ID: 80aac6f5448c
Revises: 72df5d6c7400
Create Date: 2025-09-16 07:29:21.279635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80aac6f5448c'
down_revision: Union[str, Sequence[str], None] = '72df5d6c7400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_document_messages_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_document_messages_deleted_by'),
    sa.ForeignKeyConstraint(['history_id'], ['document_histories.id'], name='fk_document_messages_history_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_document_messages_updated_by'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_document_messages_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_messages')
    # ### end Alembic commands ###
