"""relacionando imagens a users

Revision ID: 836a80fde2a7
Revises: 17903543bd7d
Create Date: 2025-11-21 13:53:07.198699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836a80fde2a7'
down_revision: Union[str, Sequence[str], None] = '17903543bd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_users_icon_id', 'users', 'user_images', ['icon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_icon_id', 'users', type_='foreignkey')
    op.drop_column('users', 'icon_id')
    # ### end Alembic commands ###
