"""

Revision ID: 85d08c533394
Revises: 517707af7e79
Create Date: 2025-09-12 09:41:24.772522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85d08c533394'
down_revision: Union[str, Sequence[str], None] = '517707af7e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_doc_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_doc_deleted_by'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_doc_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_document_histories_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_document_histories_deleted_by'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_document_histories_document_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_document_histories_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_document_releases_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_document_releases_deleted_by'),
    sa.ForeignKeyConstraint(['history_id'], ['document_histories.id'], name='fk_document_releases_history_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_document_releases_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('docs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_doc_created_by')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_doc_deleted_by')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_doc_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('docs_pkey')),
    sa.UniqueConstraint('identifier', name=op.f('docs_identifier_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('docs_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('document_releases')
    op.drop_table('document_histories')
    op.drop_table('documents')
    # ### end Alembic commands ###
