"""empty message

Revision ID: 988e3e27cd58
Revises: b2813f8606fb
Create Date: 2026-05-01 21:21:53.811250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988e3e27cd58'
down_revision: Union[str, Sequence[str], None] = 'b2813f8606fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('bundle_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'bundles', ['bundle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'bundle_id')
    # ### end Alembic commands ###
