"""move_doc_id_to_test_run

Revision ID: 9d458ebede34
Revises: 0d897444b2a4
Create Date: 2026-01-10 10:59:01.226882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d458ebede34'
down_revision: Union[str, Sequence[str], None] = '0d897444b2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uq_test_cases_name_collection_doc_active'), table_name='test_cases', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_uq_test_cases_name_collection_branch_active', 'test_cases', ['name', 'test_collection_id', 'branch_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('fk_test_cases_doc_id'), 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'doc_id')
    op.add_column('test_runs', sa.Column('doc_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_test_runs_doc_id', 'test_runs', 'documents', ['doc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_test_runs_doc_id', 'test_runs', type_='foreignkey')
    op.drop_column('test_runs', 'doc_id')
    op.add_column('test_cases', sa.Column('doc_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_test_cases_doc_id'), 'test_cases', 'documents', ['doc_id'], ['id'])
    op.drop_index('ix_uq_test_cases_name_collection_branch_active', table_name='test_cases', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_uq_test_cases_name_collection_doc_active'), 'test_cases', ['name', 'test_collection_id', 'doc_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
