"""add test_case_id to test_runs

Revision ID: a9c06671bd3a
Revises: d192ba3ccc29
Create Date: 2025-12-16 01:13:17.685710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c06671bd3a'
down_revision: Union[str, Sequence[str], None] = 'd192ba3ccc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_ai_models_updated_by', 'ai_models', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_ai_models_deleted_by', 'ai_models', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_ai_models_created_by', 'ai_models', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_metrics_created_by', 'metrics', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_metrics_deleted_by', 'metrics', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_metrics_updated_by', 'metrics', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_cases_deleted_by', 'test_cases', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_cases_created_by', 'test_cases', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_cases_updated_by', 'test_cases', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_collections_created_by', 'test_collections', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_collections_deleted_by', 'test_collections', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_collections_updated_by', 'test_collections', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_results_created_by', 'test_results', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_results_updated_by', 'test_results', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_results_deleted_by', 'test_results', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.add_column('test_runs', sa.Column('test_case_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_test_runs_created_by', 'test_runs', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_runs_test_case_id', 'test_runs', 'test_cases', ['test_case_id'], ['id'])
    op.create_foreign_key('fk_test_runs_updated_by', 'test_runs', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_test_runs_deleted_by', 'test_runs', 'users', ['deleted_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_test_runs_deleted_by', 'test_runs', type_='foreignkey')
    op.drop_constraint('fk_test_runs_updated_by', 'test_runs', type_='foreignkey')
    op.drop_constraint('fk_test_runs_test_case_id', 'test_runs', type_='foreignkey')
    op.drop_constraint('fk_test_runs_created_by', 'test_runs', type_='foreignkey')
    op.drop_column('test_runs', 'test_case_id')
    op.drop_constraint('fk_test_results_deleted_by', 'test_results', type_='foreignkey')
    op.drop_constraint('fk_test_results_updated_by', 'test_results', type_='foreignkey')
    op.drop_constraint('fk_test_results_created_by', 'test_results', type_='foreignkey')
    op.drop_constraint('fk_test_collections_updated_by', 'test_collections', type_='foreignkey')
    op.drop_constraint('fk_test_collections_deleted_by', 'test_collections', type_='foreignkey')
    op.drop_constraint('fk_test_collections_created_by', 'test_collections', type_='foreignkey')
    op.drop_constraint('fk_test_cases_updated_by', 'test_cases', type_='foreignkey')
    op.drop_constraint('fk_test_cases_created_by', 'test_cases', type_='foreignkey')
    op.drop_constraint('fk_test_cases_deleted_by', 'test_cases', type_='foreignkey')
    op.drop_constraint('fk_metrics_updated_by', 'metrics', type_='foreignkey')
    op.drop_constraint('fk_metrics_deleted_by', 'metrics', type_='foreignkey')
    op.drop_constraint('fk_metrics_created_by', 'metrics', type_='foreignkey')
    op.drop_constraint('fk_ai_models_created_by', 'ai_models', type_='foreignkey')
    op.drop_constraint('fk_ai_models_deleted_by', 'ai_models', type_='foreignkey')
    op.drop_constraint('fk_ai_models_updated_by', 'ai_models', type_='foreignkey')
    # ### end Alembic commands ###
