"""empty message

Revision ID: b2813f8606fb
Revises: 382e87b0eb8e
Create Date: 2026-05-01 07:49:38.935922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2813f8606fb'
down_revision: Union[str, Sequence[str], None] = '382e87b0eb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_document_typifications', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('bundle_document_typifications', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_bundle_document_created_by', 'bundle_document_typifications', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_bundle_documents_deleted_by', 'bundle_documents', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_bundle_documents_updated_by', 'bundle_documents', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_bundle_documents_created_by', 'bundle_documents', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_bundles_updated_by', 'bundles', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_bundles_created_by', 'bundles', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_bundles_deleted_by', 'bundles', 'users', ['deleted_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bundles_deleted_by', 'bundles', type_='foreignkey')
    op.drop_constraint('fk_bundles_created_by', 'bundles', type_='foreignkey')
    op.drop_constraint('fk_bundles_updated_by', 'bundles', type_='foreignkey')
    op.drop_constraint('fk_bundle_documents_created_by', 'bundle_documents', type_='foreignkey')
    op.drop_constraint('fk_bundle_documents_updated_by', 'bundle_documents', type_='foreignkey')
    op.drop_constraint('fk_bundle_documents_deleted_by', 'bundle_documents', type_='foreignkey')
    op.drop_constraint('fk_bundle_document_created_by', 'bundle_document_typifications', type_='foreignkey')
    op.drop_column('bundle_document_typifications', 'created_by')
    op.drop_column('bundle_document_typifications', 'created_at')
    # ### end Alembic commands ###
