"""empty message

Revision ID: cc35d1217ac6
Revises: 
Create Date: 2025-09-30 10:48:37.297270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc35d1217ac6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applied_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_unit_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_unit_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_unit_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_units_name_active', 'units', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_user_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_user_deleted_by'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='fk_user_unit_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_user_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_users_phone_number_active', 'users', ['phone_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_doc_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_doc_deleted_by'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_doc_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_documents_identifier_active', 'documents', ['identifier'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_documents_name_active', 'documents', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_source_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_source_deleted_by'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_source_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_sources_name_active', 'sources', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('typifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_typification_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_typification_deleted_by'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_typification_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_typifications_name_active', 'typifications', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('document_editors',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_doc_editor_document_id'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name='fk_doc_editor_granted_by'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_doc_editor_user_id'),
    sa.PrimaryKeyConstraint('document_id', 'user_id')
    )
    op.create_table('document_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_document_histories_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_document_histories_deleted_by'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_document_histories_document_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_document_histories_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_typifications',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_doc_typ_created_by'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_doc_typ_document_id'),
    sa.ForeignKeyConstraint(['typification_id'], ['typifications.id'], name='fk_doc_typ_typification_id'),
    sa.PrimaryKeyConstraint('document_id', 'typification_id')
    )
    op.create_table('taxonomies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_taxonomy_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_taxonomy_deleted_by'),
    sa.ForeignKeyConstraint(['typification_id'], ['typifications.id'], name='fk_taxonomy_typification_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_taxonomy_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_taxonomies_title_active', 'taxonomies', ['title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('typification_sources',
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_typ_source_created_by'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_typ_source_source_id'),
    sa.ForeignKeyConstraint(['typification_id'], ['typifications.id'], name='fk_typ_source_typification_id'),
    sa.PrimaryKeyConstraint('typification_id', 'source_id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_branch_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_branch_deleted_by'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomies.id'], name='fk_branch_taxonomy_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_branch_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_branch_title_active', 'branches', ['title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('document_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_document_messages_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_document_messages_deleted_by'),
    sa.ForeignKeyConstraint(['history_id'], ['document_histories.id'], name='fk_document_messages_history_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_document_messages_updated_by'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_document_messages_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_document_releases_created_by'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_document_releases_deleted_by'),
    sa.ForeignKeyConstraint(['history_id'], ['document_histories.id'], name='fk_document_releases_history_id'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_document_releases_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy_sources',
    sa.Column('taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_tax_source_created_by'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_tax_source_source_id'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomies.id'], name='fk_tax_source_taxonomy_id'),
    sa.PrimaryKeyConstraint('taxonomy_id', 'source_id')
    )
    op.create_table('applied_typifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('applied_release_id', sa.Uuid(), nullable=False),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_release_id'], ['document_releases.id'], name='fk_applied_typification_release_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_typification_created_by'),
    sa.ForeignKeyConstraint(['original_id'], ['typifications.id'], name='fk_applied_typification_original_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applied_taxonomies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('applied_typification_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_typification_id'], ['applied_typifications.id'], name='fk_applied_taxonomy_typification_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_taxonomy_created_by'),
    sa.ForeignKeyConstraint(['original_id'], ['taxonomies.id'], name='fk_applied_taxonomy_original_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applied_typification_sources',
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_typ_source_created_by'),
    sa.ForeignKeyConstraint(['source_id'], ['applied_sources.id'], name='fk_applied_typ_source_source_id'),
    sa.ForeignKeyConstraint(['typification_id'], ['applied_typifications.id'], name='fk_applied_typ_source_typification_id'),
    sa.PrimaryKeyConstraint('typification_id', 'source_id')
    )
    op.create_table('applied_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('applied_taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_taxonomy_id'], ['applied_taxonomies.id'], name='fk_applied_branch_taxonomy_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_branch_created_by'),
    sa.ForeignKeyConstraint(['original_id'], ['branches.id'], name='fk_applied_branch_original_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applied_taxonomy_sources',
    sa.Column('taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_tax_source_created_by'),
    sa.ForeignKeyConstraint(['source_id'], ['applied_sources.id'], name='fk_applied_tax_source_source_id'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['applied_taxonomies.id'], name='fk_applied_tax_source_taxonomy_id'),
    sa.PrimaryKeyConstraint('taxonomy_id', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applied_taxonomy_sources')
    op.drop_table('applied_branches')
    op.drop_table('applied_typification_sources')
    op.drop_table('applied_taxonomies')
    op.drop_table('applied_typifications')
    op.drop_table('taxonomy_sources')
    op.drop_table('document_releases')
    op.drop_table('document_messages')
    op.drop_index('ix_uq_branch_title_active', table_name='branches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('branches')
    op.drop_table('typification_sources')
    op.drop_index('ix_uq_taxonomies_title_active', table_name='taxonomies', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('taxonomies')
    op.drop_table('document_typifications')
    op.drop_table('document_histories')
    op.drop_table('document_editors')
    op.drop_index('ix_uq_typifications_name_active', table_name='typifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('typifications')
    op.drop_index('ix_uq_sources_name_active', table_name='sources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('sources')
    op.drop_index('ix_uq_documents_name_active', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_documents_identifier_active', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('documents')
    op.drop_index('ix_uq_users_phone_number_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('ix_uq_units_name_active', table_name='units', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('units')
    op.drop_table('applied_sources')
    # ### end Alembic commands ###
