"""mig

Revision ID: cde58d0204ca
Revises: cc35d1217ac6
Create Date: 2025-10-17 15:16:09.617664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde58d0204ca'
down_revision: Union[str, Sequence[str], None] = 'cc35d1217ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_unit_created_by', 'units', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_unit_deleted_by', 'units', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_unit_updated_by', 'units', 'users', ['updated_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unit_updated_by', 'units', type_='foreignkey')
    op.drop_constraint('fk_unit_deleted_by', 'units', type_='foreignkey')
    op.drop_constraint('fk_unit_created_by', 'units', type_='foreignkey')
    # ### end Alembic commands ###
