"""

Revision ID: ce1e18927f47
Revises: 80aac6f5448c
Create Date: 2025-09-18 13:47:11.306516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1e18927f47'
down_revision: Union[str, Sequence[str], None] = '80aac6f5448c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applied_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applied_typifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('applied_release_id', sa.Uuid(), nullable=False),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_release_id'], ['document_releases.id'], name='fk_applied_typification_release_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_typification_created_by'),
    sa.ForeignKeyConstraint(['original_id'], ['typifications.id'], name='fk_applied_typification_original_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applied_taxonomies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('applied_typification_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_typification_id'], ['applied_typifications.id'], name='fk_applied_taxonomy_typification_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_taxonomy_created_by'),
    sa.ForeignKeyConstraint(['original_id'], ['taxonomies.id'], name='fk_applied_taxonomy_original_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applied_typification_sources',
    sa.Column('typification_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_typ_source_created_by'),
    sa.ForeignKeyConstraint(['source_id'], ['applied_sources.id'], name='fk_applied_typ_source_source_id'),
    sa.ForeignKeyConstraint(['typification_id'], ['applied_typifications.id'], name='fk_applied_typ_source_typification_id'),
    sa.PrimaryKeyConstraint('typification_id', 'source_id')
    )
    op.create_table('applied_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('applied_taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_id', sa.Uuid(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_taxonomy_id'], ['applied_taxonomies.id'], name='fk_applied_branch_taxonomy_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_applied_branch_created_by'),
    sa.ForeignKeyConstraint(['original_id'], ['branches.id'], name='fk_applied_branch_original_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applied_branches')
    op.drop_table('applied_typification_sources')
    op.drop_table('applied_taxonomies')
    op.drop_table('applied_typifications')
    op.drop_table('applied_sources')
    # ### end Alembic commands ###
