"""implementação das mensagens

Revision ID: dad9f0782cdf
Revises: ba6cebecda09
Create Date: 2025-11-02 11:51:12.277180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad9f0782cdf'
down_revision: Union[str, Sequence[str], None] = 'ba6cebecda09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_message_mentions',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['document_messages.id'], name='fk_doc_msg_mention_message_id'),
    sa.PrimaryKeyConstraint('message_id', 'entity_id')
    )
    op.add_column('document_messages', sa.Column('content', sa.String(), nullable=False))
    op.add_column('document_messages', sa.Column('document_id', sa.Uuid(), nullable=False))
    op.add_column('document_messages', sa.Column('release_id', sa.Uuid(), nullable=True))
    op.add_column('document_messages', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.add_column('document_messages', sa.Column('quoted_message_id', sa.Uuid(), nullable=True))
    op.create_index('ix_doc_msg_document_id_created_at', 'document_messages', ['document_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('fk_document_messages_history_id'), 'document_messages', type_='foreignkey')
    op.drop_constraint(op.f('fk_document_messages_user_id'), 'document_messages', type_='foreignkey')
    op.create_foreign_key('fk_doc_msg_author_id', 'document_messages', 'users', ['author_id'], ['id'])
    op.create_foreign_key('fk_doc_msg_release_id', 'document_messages', 'document_releases', ['release_id'], ['id'])
    op.create_foreign_key('fk_doc_msg_quoted_message_id', 'document_messages', 'document_messages', ['quoted_message_id'], ['id'])
    op.create_foreign_key('fk_doc_msg_document_id', 'document_messages', 'documents', ['document_id'], ['id'])
    op.drop_column('document_messages', 'history_id')
    op.drop_column('document_messages', 'user_id')
    op.drop_column('document_messages', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_messages', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('document_messages', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('document_messages', sa.Column('history_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_doc_msg_document_id', 'document_messages', type_='foreignkey')
    op.drop_constraint('fk_doc_msg_quoted_message_id', 'document_messages', type_='foreignkey')
    op.drop_constraint('fk_doc_msg_release_id', 'document_messages', type_='foreignkey')
    op.drop_constraint('fk_doc_msg_author_id', 'document_messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_document_messages_user_id'), 'document_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_document_messages_history_id'), 'document_messages', 'document_histories', ['history_id'], ['id'])
    op.drop_index('ix_doc_msg_document_id_created_at', table_name='document_messages')
    op.drop_column('document_messages', 'quoted_message_id')
    op.drop_column('document_messages', 'author_id')
    op.drop_column('document_messages', 'release_id')
    op.drop_column('document_messages', 'document_id')
    op.drop_column('document_messages', 'content')
    op.drop_table('document_message_mentions')
    # ### end Alembic commands ###
