"""removendo regras de unicidade

Revision ID: f27a3617d826
Revises: 04f324aaecb3
Create Date: 2025-09-19 18:10:36.999312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27a3617d826'
down_revision: Union[str, Sequence[str], None] = '04f324aaecb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branches_title_key'), 'branches', type_='unique')
    op.drop_constraint(op.f('documents_identifier_key'), 'documents', type_='unique')
    op.drop_constraint(op.f('documents_name_key'), 'documents', type_='unique')
    op.drop_constraint(op.f('sources_name_key'), 'sources', type_='unique')
    op.drop_constraint(op.f('taxonomies_title_key'), 'taxonomies', type_='unique')
    op.drop_constraint(op.f('typifications_name_key'), 'typifications', type_='unique')
    op.drop_constraint(op.f('units_name_key'), 'units', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('units_name_key'), 'units', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('typifications_name_key'), 'typifications', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('taxonomies_title_key'), 'taxonomies', ['title'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('sources_name_key'), 'sources', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('documents_name_key'), 'documents', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('documents_identifier_key'), 'documents', ['identifier'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('branches_title_key'), 'branches', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
