"""estabilizando

Revision ID: f49458ae444c
Revises: c16dca6e0f2c
Create Date: 2025-10-22 14:33:44.220113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49458ae444c'
down_revision: Union[str, Sequence[str], None] = 'c16dca6e0f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('unit_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'documents', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'unit_id')
    # ### end Alembic commands ###
