"""SET NULL icon

Revision ID: fce075e65e07
Revises: 453fbd69a0e7
Create Date: 2026-02-02 19:55:44.966469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce075e65e07'
down_revision: Union[str, Sequence[str], None] = '453fbd69a0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_icon_id'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_icon_id', 'users', 'user_images', ['icon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_icon_id', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_icon_id'), 'users', 'user_images', ['icon_id'], ['id'])
    # ### end Alembic commands ###
